# Generated by Django 4.2.7 on 2023-11-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15, verbose_name='Category Name:')),
                ('description', models.TextField(verbose_name='Description:')),
                ('picture', models.BinaryField(verbose_name='Picture:')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40, verbose_name='Company Name:')),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Name:')),
                ('contact_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Title:')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='Address:')),
                ('city', models.CharField(blank=True, max_length=15, null=True, verbose_name='City:')),
                ('region', models.CharField(blank=True, max_length=15, null=True, verbose_name='Region:')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code:')),
                ('country', models.CharField(blank=True, max_length=15, null=True, verbose_name='Country:')),
                ('phone', models.CharField(blank=True, max_length=24, null=True, verbose_name='Phone:')),
                ('fax', models.CharField(blank=True, max_length=24, null=True, verbose_name='Fax:')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name:')),
                ('first_name', models.CharField(max_length=10, verbose_name='First Name:')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title:')),
                ('title_of_courtesy', models.CharField(blank=True, max_length=25, null=True, verbose_name='Title of Courtesy:')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('hire_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=24, null=True)),
                ('extension', models.CharField(blank=True, max_length=4, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('required_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('freight', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ship_name', models.CharField(blank=True, max_length=40, null=True)),
                ('ship_address', models.CharField(blank=True, max_length=60, null=True)),
                ('ship_city', models.CharField(blank=True, max_length=15, null=True)),
                ('ship_region', models.CharField(blank=True, max_length=15, null=True)),
                ('ship_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ship_country', models.CharField(blank=True, max_length=15, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40, verbose_name='Company Name:')),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Name:')),
                ('contact_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Estacion:')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre Estacion:')),
                ('city', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nombre Estacion:')),
                ('region', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nombre Estacion:')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre Estacion:')),
                ('country', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nombre Estacion:')),
                ('phone', models.CharField(blank=True, max_length=24, null=True, verbose_name='Nombre Estacion:')),
                ('fax', models.CharField(blank=True, max_length=24, null=True, verbose_name='Nombre Estacion:')),
                ('homepage', models.TextField(blank=True, null=True, verbose_name='Nombre Estacion:')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40, verbose_name='Product Name:')),
                ('quantity_per_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Quantity Per Unit:')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Unit Price:')),
                ('units_in_stock', models.SmallIntegerField(default=0, verbose_name='Units In Stock:')),
                ('units_on_order', models.SmallIntegerField(default=0, verbose_name='Units On Order:')),
                ('reorder_level', models.SmallIntegerField(default=0, verbose_name='Reorder Level:')),
                ('discontinued', models.BooleanField(default=False, verbose_name='Discontinued:')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('discount', models.FloatField(default=0)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ship_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shipper'),
        ),
    ]
